<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Patient', 'doctrine');

/**
 * BasePatient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $firstname
 * @property string $lastname
 * @property date $birthdate
 * @property string $address
 * @property string $zip
 * @property string $city
 * @property Doctrine_Collection $Event
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getFirstname() Returns the current record's "firstname" value
 * @method string              getLastname()  Returns the current record's "lastname" value
 * @method date                getBirthdate() Returns the current record's "birthdate" value
 * @method string              getAddress()   Returns the current record's "address" value
 * @method string              getZip()       Returns the current record's "zip" value
 * @method string              getCity()      Returns the current record's "city" value
 * @method Doctrine_Collection getEvent()     Returns the current record's "Event" collection
 * @method Patient             setId()        Sets the current record's "id" value
 * @method Patient             setFirstname() Sets the current record's "firstname" value
 * @method Patient             setLastname()  Sets the current record's "lastname" value
 * @method Patient             setBirthdate() Sets the current record's "birthdate" value
 * @method Patient             setAddress()   Sets the current record's "address" value
 * @method Patient             setZip()       Sets the current record's "zip" value
 * @method Patient             setCity()      Sets the current record's "city" value
 * @method Patient             setEvent()     Sets the current record's "Event" collection
 * 
 * @package    paramedical
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePatient extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patient');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('firstname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('lastname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('birthdate', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('address', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('zip', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 5,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Event', array(
             'local' => 'id',
             'foreign' => 'patient_id'));
    }
}