<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Event', 'doctrine');

/**
 * BaseEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property datetime $date
 * @property string $title
 * @property string $descritpion
 * @property integer $patient_id
 * @property integer $consultant_id
 * @property Patient $Patient
 * @property Consultant $Consultant
 * 
 * @method integer    getId()            Returns the current record's "id" value
 * @method datetime   getDate()          Returns the current record's "date" value
 * @method string     getTitle()         Returns the current record's "title" value
 * @method string     getDescritpion()   Returns the current record's "descritpion" value
 * @method integer    getPatientId()     Returns the current record's "patient_id" value
 * @method integer    getConsultantId()  Returns the current record's "consultant_id" value
 * @method Patient    getPatient()       Returns the current record's "Patient" value
 * @method Consultant getConsultant()    Returns the current record's "Consultant" value
 * @method Event      setId()            Sets the current record's "id" value
 * @method Event      setDate()          Sets the current record's "date" value
 * @method Event      setTitle()         Sets the current record's "title" value
 * @method Event      setDescritpion()   Sets the current record's "descritpion" value
 * @method Event      setPatientId()     Sets the current record's "patient_id" value
 * @method Event      setConsultantId()  Sets the current record's "consultant_id" value
 * @method Event      setPatient()       Sets the current record's "Patient" value
 * @method Event      setConsultant()    Sets the current record's "Consultant" value
 * 
 * @package    paramedical
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'notnull' => false,
             ));
        $this->hasColumn('date', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descritpion', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('patient_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('consultant_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Patient', array(
             'local' => 'patient_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Consultant', array(
             'local' => 'consultant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}