<?php

/**
 * ConsultantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConsultantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConsultantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Consultant');
    }

	public function findConsultantList()
	{
	  $consultants     = array();
	  $consultants[''] = '';
	  $modelConsultant = $this->getInstance()->findAll();
	  foreach ($modelConsultant as $consultant) {
	      $consultants[$consultant->getId()] = $consultant->getFirstname().' '.$consultant->getLastname();
	  }
	  return $consultants;
	}


}