<?php

/**
 * ConsultantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConsultantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConsultantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Consultant');
    }
}