<?php

/**
 * EventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Event');
    }

    public function countCurrentEventByConsultantId($consultantId) 
    {
    	return $this->createQuery()
	        ->where('consultant_id = ? AND DATE(date) = ?', array($consultantId, date('Y-m-d')))
	        ->count();
    }
}