<?php

/**
 * PatientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PatientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PatientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Patient');
    }

    public function findBySearchKeywords($search)
    {
    	return $this->createQuery()
	        ->where('firstname LIKE ? OR lastname LIKE ?', array('%' . $search . '%', '%' . $search . '%'))
	        ->execute();
    }
}