# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: patient, action: list }

# Login management
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# Patient module
patient_list:
  url: /patient
  param: { module: patient, action: list }

patient_show:
  url: /patient/show/:id
  class: sfDoctrineRoute
  options: { model: patient, type: object }
  param: { module: patient, action: show, id:0 }

patient_create:
  url: /patient/create
  param: { module: patient, action: create }

patient_new:
  url: /patient/new
  param: { module: patient, action: new }

patient_update:
  url: /patient/:id
  class: sfDoctrineRoute
  options: { model: patient, type: object }
  param: { module: patient, action: update, id:0 }

# Consultant module
consultant_show:
  url: /consultant/show/:id
  class: sfDoctrineRoute
  options: { model: consultant, type: object }
  param: { module: consultant, action: show, id:0 }

consultant_update:
  url: /consultant/:id
  class: sfDoctrineRoute
  options: { model: consultant, type: object }
  param: { module: consultant, action: update, id:0 }
  requirements: { sf_method:  [get, post] }

# Calendar module
calendar_show:
  url: /calendar
  param: { module: calendar, action: show }




patient_event_create:
  url: /patient/:id/event/create
  param: { module: patient, action: eventCreate }

