# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Paramedical
    #language:     en
    #description:  symfony project
    #keywords:     symfony, project
    #robots:       index, follow

  stylesheets:
    - main.css
    - sfJqueryReloadedPlugin/JqueryAutocomplete.css
    - sfJqueryReloadedPlugin/ui-lightness/jquery-ui-1.8.2.custom.css

  javascripts:
    - sfJqueryReloadedPlugin/jquery-1.4.2.min.js
    - sfJqueryReloadedPlugin/jquery-1.3.2.min.js
    - sfJqueryReloadedPlugin/plugins/jquery-ui-1.7.3.custom.min.js

  has_layout:     true
  layout:         layout
