<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/10/17 17:38:33
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => false,
  'app_sf_guard_plugin_sf_guard_plugin_routes_register' => false,
));
