<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/10/11 20:22:10
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => 'C:/dev/source/symfony/paramedical/lib/vendor/symfony-1.4.2/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'baseconsultantformfilter' => 'C:/dev/source/symfony/paramedical/lib/filter/doctrine/base/BaseConsultantFormFilter.class.php',
  'baseeventformfilter' => 'C:/dev/source/symfony/paramedical/lib/filter/doctrine/base/BaseEventFormFilter.class.php',
  'basepatientformfilter' => 'C:/dev/source/symfony/paramedical/lib/filter/doctrine/base/BasePatientFormFilter.class.php',
  'baseformfilterdoctrine' => 'C:/dev/source/symfony/paramedical/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'consultantformfilter' => 'C:/dev/source/symfony/paramedical/lib/filter/doctrine/ConsultantFormFilter.class.php',
  'eventformfilter' => 'C:/dev/source/symfony/paramedical/lib/filter/doctrine/EventFormFilter.class.php',
  'patientformfilter' => 'C:/dev/source/symfony/paramedical/lib/filter/doctrine/PatientFormFilter.class.php',
  'baseform' => 'C:/dev/source/symfony/paramedical/lib/form/BaseForm.class.php',
  'baseconsultantform' => 'C:/dev/source/symfony/paramedical/lib/form/doctrine/base/BaseConsultantForm.class.php',
  'baseeventform' => 'C:/dev/source/symfony/paramedical/lib/form/doctrine/base/BaseEventForm.class.php',
  'basepatientform' => 'C:/dev/source/symfony/paramedical/lib/form/doctrine/base/BasePatientForm.class.php',
  'baseformdoctrine' => 'C:/dev/source/symfony/paramedical/lib/form/doctrine/BaseFormDoctrine.class.php',
  'consultantform' => 'C:/dev/source/symfony/paramedical/lib/form/doctrine/ConsultantForm.class.php',
  'eventform' => 'C:/dev/source/symfony/paramedical/lib/form/doctrine/EventForm.class.php',
  'patientform' => 'C:/dev/source/symfony/paramedical/lib/form/doctrine/PatientForm.class.php',

  // project_model
  'baseconsultant' => 'C:/dev/source/symfony/paramedical/lib/model/doctrine/base/BaseConsultant.class.php',
  'baseevent' => 'C:/dev/source/symfony/paramedical/lib/model/doctrine/base/BaseEvent.class.php',
  'basepatient' => 'C:/dev/source/symfony/paramedical/lib/model/doctrine/base/BasePatient.class.php',
  'consultant' => 'C:/dev/source/symfony/paramedical/lib/model/doctrine/Consultant.class.php',
  'consultanttable' => 'C:/dev/source/symfony/paramedical/lib/model/doctrine/ConsultantTable.class.php',
  'event' => 'C:/dev/source/symfony/paramedical/lib/model/doctrine/Event.class.php',
  'eventtable' => 'C:/dev/source/symfony/paramedical/lib/model/doctrine/EventTable.class.php',
  'patient' => 'C:/dev/source/symfony/paramedical/lib/model/doctrine/Patient.class.php',
  'patienttable' => 'C:/dev/source/symfony/paramedical/lib/model/doctrine/PatientTable.class.php',

  // application
  'myuser' => 'C:/dev/source/symfony/paramedical/apps/backend/lib/myUser.class.php',

  // modules
);
