<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/10/13 20:00:23
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
