<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/10/13 19:58:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=paramedical',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
